### ISSUE TITLE
[Bug] ESM build not interpreted as a module in node v14+

### ISSUE THREAD

**Issue by julbd** [storybookjs/telejson#78]
### Describe the bug

Importing the latest version of `telejson` using ESM `import` in node v14+ crashes with the error below.
This could be due to a missing package.json:`"type": "module",` in the `dist/esm/` build directory.

⚠️  There is no error in v5.0.2.

### Steps to reproduce the behavior

> package.json
```
    ...
    "type": "module",
    ...
```

> myapp/index.js
```
import telejson from "telejson";
...
```

### Screenshots and/or logs

```
(node:2809) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/Users/path/to/myapp/node_modules/telejson/dist/esm/index.js:19
import isRegExp from 'is-regex';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at ModuleWrap.<anonymous> (internal/modules/esm/translators.js:199:29)
    at ModuleJob.run (internal/modules/esm/module_job.js:183:25)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
```

### Environment

 - OS: macOS 12.1
 - Node.js version: v14.18.3
 - NPM version: 8

**Comment by julbd** [comment]
@ndelangen
